React Developer Tools
reactjs/cs.react.dev pull request #18
Opened 2023-06-01 13:28 UTC by danielkraus

Closes https://github.com/reactjs/cs.react.dev/issues/10

2023-06-01 17:37 UTC, pchalupa requested changes
Well done sir! I left some comments. I am not sure about capitals in the words `Terminal` and `Vývojářské nástroje`. I also added a comment about `i` vs `y. Overall this is a good translation! 👏

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +title: Vývojářské nástroje Reactu
What do you think about changing the form?
```suggestion
title: Vývojářské nástroje pro React
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +* Jak nainstalovat Vývojářské nástroje Reactu
I am not sure about the capital v in "Vývojářské" and maybe we can add "si".
```suggestion
* Jak si nainstalovat vývojářské nástroje Reactu
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +Nejjednodušší způsob, jak ladit webové stránky vytvořené pomocí Reactu, je nainstalovat si Vývojářské nástroje Reactu jako rozšíření do vašeho prohlížeče. Tyto nástroje jsou k dispozici pro následují
I think we can skip "vašeho". I am also not sure about the capital v.
```suggestion
Nejjednodušší způsob, jak ladit webové stránky vytvořené pomocí Reactu, je nainstalovat si vývojářské nástroje Reactu jako rozšíření do prohlížeče. Tyto nástroje jsou k dispozici pro následující prohlížeče:
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +Když po instalaci navštívíte jakoukoliv webovou stránku **vytvořenou v Reactu,** uvidíte panely s názvy _Components_ a _Profiler_.
A bit different form.
```suggestion
Nyní, když navštívíte jakoukoliv webovou stránku **vytvořenou v Reactu,** uvidíte panely s názvy _Components_ a _Profiler_.
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +npm install -g react-devtools/
This is probably typo.
```suggestion
npm install -g react-devtools
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +> Zkuste obnovit aplikaci pokud se nástroje po několika sekundách nepřipojí sami.
I think, there should be y. I found this description https://www.pravopisne.cz/2015/02/samy-x-sami/.
```suggestion
> Zkuste obnovit aplikaci pokud se nástroje po několika sekundách nepřipojí samy.
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +Nástroje se nyní sami spojí s vaší React Native aplikací, která běží v lokálním prostředí.
Same comment as the next one, line 73.
```suggestion
Nástroje se nyní samy spojí s vaší React Native aplikací, která běží v lokálním prostředí.
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +Poté nástroje otevřte v Terminálu:
I think there should be no capital T.
```suggestion
Poté nástroje otevřte v terminálu:
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +Nyní obnovte stránku v prohlížeči a uvidíte Vývojářské nástroje.
```suggestion
Nyní obnovte stránku v prohlížeči a uvidíte vývojářské nástroje.
```

2023-06-01 17:37 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
> +Poté otevřte tyto nástroje pomocí Terminálu:
```suggestion
Poté otevřte tyto nástroje pomocí terminálu:
```

2023-06-02 06:36 UTC, danielkraus commented
@pchalupa Thanks for the suggestions! 

1. I'm pretty sure Terminal should go with capital T – it's a name, see official Apple docs of Apple Czech https://support.apple.com/cs-cz/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac
2. Not that obvious with "Vyvojarske nastroje pro React" but it's a translated name that refers to a specific tool/app. If you keep "vyvojarske nastroje", that means you refer to any tool. There's also an option to keep calling it "React Developer Tools" as it's the only official way and the tool itself is not translated anyway. Similar how Google does here https://support.google.com/adsense/answer/10858959?hl=cs&sjid=3729838083219203571-EU. Thoughts?

2023-06-02 07:19 UTC, pchalupa commented
> @pchalupa Thanks for the suggestions!
> 
> 1. I'm pretty sure Terminal should go with capital T – it's a name, see official Apple docs in Czech https://support.apple.com/cs-cz/guide/terminal/apd5265185d-f365-44cb-8b09-71a064a42125/mac
> 2. Not that obvious with "Vyvojarske nastroje pro React" but it's a translated name that refers to a specific tool/app. If you keep "vyvojarske nastroje", that means you refer to any tool. There's also an option to keep calling it "React Developer Tools" as it's the only official way and the tool itself is not translated anyway. Similar how Google does here https://support.google.com/adsense/answer/10858959?hl=cs&sjid=3729838083219203571-EU. Thoughts?

You are correct, the Terminal on Mac is with capital, but I think it is meant as a general terminal app in this context. You can use these tools on Windows, Linux, etc... and these systems have their own terminals.
I think with the "vývojářské nástroje" is similar to saying "hdyratační krém", but if you add the brand like "hydratační krém Nivea" then the capital letter is correct. I am open for discussion.

2023-06-05 09:14 UTC, pchalupa commented on src/content/learn/react-developer-tools.md
>  <YouWillLearn>
Could you please check this component? The title is in en.

2023-06-05 10:43 UTC, pchalupa approved these changes

2023-06-06 14:34 UTC, merged